import { useEffect, useRef } from 'react'
import Phaser from 'phaser'
import { BUILDING_STATS, fromGrid, GRID_SIZE, isPlacementValid, toGrid } from './game'
import type { Building } from './game'
import { useGameStore } from './store'

const colors: Record<string, number> = { food: 0x76b852, wood: 0x7b4f2d, stone: 0x9aa4ad, gold: 0xf0c44c }
class RTSScene extends Phaser.Scene {
  private last = 0
  private dragStart?: Phaser.Math.Vector2
  constructor() { super('rts') }
  create() { this.cameras.main.setBounds(0, 0, 2100, 1200); this.cameras.main.setZoom(0.82); this.input.on('pointermove', (pointer: Phaser.Input.Pointer) => { const state = useGameStore.getState(); if (state.placement) { const snapped = fromGrid(toGrid({ x: pointer.worldX, y: pointer.worldY })); state.updatePreview(snapped.x, snapped.y) } }); this.input.on('pointerdown', (pointer: Phaser.Input.Pointer) => { if (pointer.middleButtonDown()) return; const state = useGameStore.getState(); if (pointer.leftButtonDown() && state.placement) { state.confirmPlacement(); return } if (pointer.leftButtonDown()) this.dragStart = new Phaser.Math.Vector2(pointer.worldX, pointer.worldY) }); this.input.on('pointerup', (pointer: Phaser.Input.Pointer) => { const store = useGameStore.getState(); if (pointer.button === 2) { if (store.placement) { store.cancelPlacement(); return } const hit = this.hit(pointer.worldX, pointer.worldY); if (hit?.kind === 'node') store.gatherSelected(hit.id); else if (hit) store.attack(hit.id); else store.moveSelected(pointer.worldX, pointer.worldY) } if (pointer.button === 0 && this.dragStart) { const distance = Phaser.Math.Distance.Between(this.dragStart.x, this.dragStart.y, pointer.worldX, pointer.worldY); if (distance > 14) { const x1 = Math.min(this.dragStart.x, pointer.worldX); const x2 = Math.max(this.dragStart.x, pointer.worldX); const y1 = Math.min(this.dragStart.y, pointer.worldY); const y2 = Math.max(this.dragStart.y, pointer.worldY); store.select(store.units.filter((u) => u.faction === 'player' && u.x >= x1 && u.x <= x2 && u.y >= y1 && u.y <= y2).map((u) => u.id)) } else { const hit = this.hit(pointer.worldX, pointer.worldY); store.select(hit ? [hit.id] : []) } this.dragStart = undefined } }); this.input.on('wheel', (_pointer: Phaser.Input.Pointer, _over: unknown, _dx: number, dy: number) => { this.cameras.main.setZoom(Phaser.Math.Clamp(this.cameras.main.zoom - dy * 0.0007, 0.55, 1.2)) }); this.input.keyboard?.on('keydown-W', () => this.cameras.main.scrollY -= 100); this.input.keyboard?.on('keydown-S', () => this.cameras.main.scrollY += 100); this.input.keyboard?.on('keydown-A', () => this.cameras.main.scrollX -= 100); this.input.keyboard?.on('keydown-D', () => this.cameras.main.scrollX += 100); this.input.keyboard?.on('keydown-ESC', () => useGameStore.getState().cancelPlacement()) }
  hit(x: number, y: number): { id: string; kind: 'node' | 'unit' | 'building' } | undefined { const state = useGameStore.getState(); const unit = state.units.find((u) => u.state !== 'dead' && Math.hypot(u.x - x, u.y - y) < 28); if (unit) return { id: unit.id, kind: 'unit' }; const building = state.buildings.find((b) => Math.abs(b.x - x) < 70 && Math.abs(b.y - y) < 60); if (building) return { id: building.id, kind: 'building' }; const node = state.nodes.find((n) => n.amount > 0 && Math.hypot(n.x - x, n.y - y) < 34); return node ? { id: node.id, kind: 'node' } : undefined }
  update(time: number) { const dt = Math.min((time - this.last) / 1000, 0.05); this.last = time; useGameStore.getState().tick(dt); this.draw() }
  draw() { this.children.removeAll(); const g = this.add.graphics(); g.fillStyle(0x1a302c); g.fillRect(0, 0, 2100, 1200); g.fillStyle(0x254e43); for (let x = 0; x < 2100; x += 80) for (let y = 0; y < 1200; y += 80) g.fillRect(x + 2, y + 2, 76, 76); const state = useGameStore.getState(); state.nodes.forEach((n) => { if (n.amount <= 0) return; g.fillStyle(colors[n.type]); g.fillCircle(n.x, n.y, 22); g.lineStyle(2, 0xdde5ce); g.strokeCircle(n.x, n.y, 23) }); state.buildings.forEach((b) => this.drawBuilding(b)); state.units.filter((u) => u.state !== 'dead').forEach((u) => { const color = u.faction === 'player' ? 0x58d0a8 : 0xd75a5a; g.fillStyle(color); g.fillCircle(u.x, u.y, u.type === 'commander' ? 15 : 11); if (state.selectedIds.includes(u.id)) { g.lineStyle(3, 0xffe27a); g.strokeCircle(u.x, u.y, 18) } if (u.carryingAmount) { g.fillStyle(colors[u.carrying ?? 'food']); g.fillCircle(u.x, u.y - 16, 4) } }); if (state.placement && state.preview) this.drawPreview(state.placement, state.preview.x, state.preview.y); if (this.dragStart) { const p = this.input.activePointer; this.add.rectangle((this.dragStart.x + p.worldX) / 2, (this.dragStart.y + p.worldY) / 2, Math.abs(p.worldX - this.dragStart.x), Math.abs(p.worldY - this.dragStart.y), 0x9be7cf, 0.18).setStrokeStyle(2, 0x9be7cf) } }
  drawPreview(type: keyof typeof BUILDING_STATS, x: number, y: number) { const state = useGameStore.getState(); const footprint = BUILDING_STATS[type].footprint; const origin = toGrid({ x: x - footprint.width * GRID_SIZE / 2, y: y - footprint.height * GRID_SIZE / 2 }); const valid = isPlacementValid(type, origin, 53, 30, state.buildings, state.nodes); const g = this.add.graphics(); g.fillStyle(valid ? 0x76d68a : 0xe05b5b, 0.35); g.fillRect(x - footprint.width * GRID_SIZE / 2, y - footprint.height * GRID_SIZE / 2, footprint.width * GRID_SIZE, footprint.height * GRID_SIZE); g.lineStyle(3, valid ? 0x76d68a : 0xe05b5b); g.strokeRect(x - footprint.width * GRID_SIZE / 2, y - footprint.height * GRID_SIZE / 2, footprint.width * GRID_SIZE, footprint.height * GRID_SIZE) }
  drawBuilding(b: Building) { const state = useGameStore.getState(); const footprint = BUILDING_STATS[b.type].footprint; const width = footprint.width * GRID_SIZE; const height = footprint.height * GRID_SIZE; const color = b.faction === 'player' ? 0x3b8fc2 : 0xb54252; const g = this.add.graphics(); g.fillStyle(color, b.progress < 1 ? 0.45 : 1); g.fillRoundedRect(b.x - width / 2, b.y - height / 2, width, height, 8); g.lineStyle(state.selectedIds.includes(b.id) ? 4 : 2, state.selectedIds.includes(b.id) ? 0xffe27a : 0xdde5ce); g.strokeRoundedRect(b.x - width / 2, b.y - height / 2, width, height, 8); if (b.progress < 1) { g.fillStyle(0x1b2522); g.fillRect(b.x - width / 2, b.y - height / 2 - 12, width, 6); g.fillStyle(0xe9bb66); g.fillRect(b.x - width / 2, b.y - height / 2 - 12, width * b.progress, 6) } else if (b.health < BUILDING_STATS[b.type].maxHealth || state.selectedIds.includes(b.id)) { g.fillStyle(0x311a1a); g.fillRect(b.x - width / 2, b.y - height / 2 - 10, width, 5); g.fillStyle(0x76d68a); g.fillRect(b.x - width / 2, b.y - height / 2 - 10, width * Math.max(0, b.health / BUILDING_STATS[b.type].maxHealth), 5) } }
}
export function GameCanvas() { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const game = new Phaser.Game({ type: Phaser.AUTO, width: '100%', height: '100%', parent: ref.current, backgroundColor: '#1a302c', scene: [RTSScene], scale: { mode: Phaser.Scale.RESIZE, autoCenter: Phaser.Scale.CENTER_BOTH } }); return () => game.destroy(true) }, []); return <div className="game-canvas" ref={ref} /> }
export function MiniMap() { const state = useGameStore(); return <div className="minimap" onClick={(e) => { const rect = e.currentTarget.getBoundingClientRect(); state.setCamera({ x: ((e.clientX - rect.left) / rect.width) * 2100, y: ((e.clientY - rect.top) / rect.height) * 1200 }) }}><div className="mini-base player" /><div className="mini-base enemy" />{state.nodes.map((n) => <span key={n.id} className="mini-node" style={{ left: `${n.x / 21}%`, top: `${n.y / 12}%`, background: `#${colors[n.type].toString(16)}` }} />)}</div> }
export function selectedUnitLabel(): string { const state = useGameStore.getState(); const selected = state.selectedIds[0]; const unit = state.units.find((u) => u.id === selected); if (unit) return unit.type === 'worker' ? 'عامل' : unit.type === 'swordsman' ? 'مقاتل' : unit.type === 'archer' ? 'رامٍ' : unit.type === 'cavalry' ? 'فارس' : 'قائد'; const building = state.buildings.find((b) => b.id === selected); return building ? 'مبنى' : 'لا يوجد تحديد' }
